layout_spectrum: 1
color:
  saturation: 0
  lightness: 0.983871
  brandStrength: 0.7204301
  brandColors:
    - '#FFFFFF'
    - '#F5BE7D'
    - '#F7931C'
    - '#000000'
    - '#606060'
  rhythmicContrast: 1
typography_spectrum: 0.4408602
name: Follow The Giraffe
